version: '3.5'

services:
  # 1. 启动mongo docker-compose up -d mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    network_mode: bridge
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: z5t88ya7KncMUSBa8yrmh2F60JRSJp!
    volumes:
      - ./data:/data/db
    sysctls:
      net.core.somaxconn: 16384

  # 2. 初始化yapi数据库
  # docker run -it --rm \
  # --link mongo:mongo \
  # --entrypoint npm \
  # --workdir /yapi/vendors \
  # -v $PWD/config.json:/yapi/config.json \
  # registry.cn-hangzhou.aliyuncs.com/anoyi/yapi \
  # run install-server

  # 3. 启动yapi服务
  # docker-compose up -d yapi
  yapi:
    image: registry.cn-hangzhou.aliyuncs.com/anoyi/yapi
    container_name: yapi
    working_dir: /yapi/vendors
    command: server/app.js
    ports:
      - 3000:3000
    volumes:
      - $PWD/config.json:/yapi/config.json
    links:
      - mongo
