apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloned-pvc
spec:
  storageClassName: my-csi-plugin
  ##################################
  # 卷克隆: 基于现有 PVC 创建新的 PVC 申领
  dataSource:
    name: existing-src-pvc-name
    kind: PersistentVolumeClaim
  ##################################
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc
spec:
  storageClassName: csi-hostpath-sc
  ##################################
  # 基于卷快照创建 PVC 申领 : 仅支持树外 CSI 卷插件
  dataSource:
    name: new-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  ##################################
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
