--[[
--Filename: /Users/ysj/knownsec/studynotes/lua/operators.lua
--Path: /Users/ysj/knownsec/studynotes/lua
--Created Date: Tuesday, October 24th 2023, 4:26:33 pm
--Author: ysj
--
--Copyright (c) 2023 knownsec
--]]

-- 操作符	描述	实例
-- +	加法	A + B 输出结果 30
-- -	减法	A - B 输出结果 -10
-- *	乘法	A * B 输出结果 200
-- /	除法	B / A 输出结果 2
-- %	取余	B % A 输出结果 0
-- ^	乘幂	A^2 输出结果 100
-- -	负号	-A 输出结果 -10
-- //	整除	5//2 输出结果 2
-- ==	等于	 (A == B) 为 false
-- ~=	不等于	 (A ~= B) 为 true
-- >	大于	 (A > B) 为 false
-- <	小于     (A < B) 为 true
-- >=	大于等于  (A >= B) 返回 false
-- <=	小于等于  (A <= B) 返回 true
-- and	逻辑与	  (A and B) 为 false
-- or	逻辑或	  (A or B) 为 true
-- not	逻辑非    not(A and B) 为 true
-- ..	连接两个字符串	                 a..b ，其中 a 为 "Hello " ， b 为 "World", 输出结果为 "Hello World"。
-- #	一元运算符，返回字符串或表的长度。	#"Hello" 返回 5
