apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    requests.nvidia.com/gpu: "4"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    pods: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    services.loadbalancers: "2"
# kubectl create namespace quota-example
# kubectl apply -f resource-quota.yaml --namespace=quota-example
# kubectl get quota --namespace=quota-example
# kubectl get resourcequota compute-resources --namespace=quota-example --output=yaml
# kubectl get resourcequota object-counts --namespace=quota-example --output=yaml
# kubectl describe quota compute-resources --namespace=myspace