version: '3'

services:
  etcd:
    image: 'bitnami/etcd:latest'
    container_name: etcd
    network_mode: bridge
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_ENABLE_V2=true
    ports:
      - 2379:2379
      - 2380:2380
    # volumes:
    # - /path/to/etcd.conf.yml:/opt/bitnami/etcd/conf/etcd.conf.yml
