FROM golang:1.15-alpine
RUN sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories
RUN apk --update --no-cache add mariadb-client g++ rsync openssh
RUN go env -w GOPROXY=https://goproxy.cn,direct