Name: access-api
Host: 0.0.0.0
Port: 8009
Mode: dev
Timeout: 120000
MaxBytes: 104857600

AccessRpc:
  Etcd:
    Hosts:
      - svc-etcd-cluster:2379
    Key: access.rpc
  Timeout: 120000

UsersRpc:
  Etcd:
    Hosts:
      - svc-etcd-cluster:2379
    Key: users.rpc
  Timeout: 120000

CacheRedis:
  - Host: svc-redis:6379
    Pass:
    Type: node # cluster

Auth:
  AccessSecret: bW9uZ28gMTAuMjUyLjIuOToyNzAxNy9hZG1pbi
  AccessExpire: 28800

Log:
  ServiceName: access-api
  Mode: console
  Encoding: json
  Level: info

# jaeger
Telemetry:
  Name: access-api
  Endpoint: http://svc-jaeger:14268/api/traces
  Batcher: jaeger
