# 这两行可省略
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization

namespace: scana

resources:
  - deployment.yaml
  - svc.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: deploy-mynginx
    patch: |-
      - op: add
        path: /spec/revisionHistoryLimit
        value: 5

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: deploy-mynginx
    path: patch.json

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: deploy-mynginx
    path: patch.yaml
