################################################
## ConfigMap: 用来将非机密性的数据保存到键值对中
# - 在 ConfigMap中保存的数据不可超过 1 MiB
################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  labels:
    app: myapplication
data:
  ################################################
  ####### 每个键会变成 mountPath 下面的一个文件名 #####
  
  # 类属性键；每一个键都映射到一个简单的值
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"

  # 类文件键
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
################################################
## 创建不可变更的 ConfigMap
immutable: true 
################################################

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      
      ########################################################################
      # 以环境变量方式使用的 ConfigMap 数据不会被自动更新。 更新这些数据需要重新启动 Pod。
      env: 
        # 定义环境变量
        - name: PLAYER_INITIAL_LIVES # 请注意这里和 ConfigMap 中的键名是不一样的
          valueFrom:
            configMapKeyRef:
              name: myconfigmap # 这个值来自 ConfigMap
              key: player_initial_lives # 需要取值的键
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: myconfigmap
              key: ui_properties_file_name
      ########################################################################

      ########################################################################
      # 当卷中使用的 ConfigMap 被更新时，所投射的键最终也会被更新。
      # 以 subPath 形式挂载的， 无法收到自动的 ConfigMap 更新。
      volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      ########################################################################
  volumes:
    # 你可以在 Pod 级别设置卷，然后将其挂载到 Pod 内的容器中
    - name: config
      configMap:
        # 提供你想要挂载的 ConfigMap 的名字
        name: myconfigmap
        # 来自 ConfigMap 的一组键，将被创建为文件
        items:
          - key: "game.properties"
            path: "game.properties"
          - key: "user-interface.properties"
            path: "user-interface.properties"
