apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
    - port: 8000
      targetPort: 3306
  clusterIP: None
## 无头服务
# 通过指定 spec.clusterIP的值为 "None" 来创建 Headless Service
# 不会分配 Cluster IP，kube-proxy 不会处理它们，也不会进行负载均衡和路由
#——带选择算符：Endpoints 控制器会创建 Endpoints 记录， 并且修改 DNS 配置
#——不带选择算符：Endpoints 控制器不会创建 Endpoints 记录，但DNS始终会查找与 Service 名称相同的任何 Endpoints 记录
