apiVersion: kubescheduler.config.k8s.io/v1beta3
kind: KubeSchedulerConfiguration

profiles:
  - schedulerName: default-scheduler
  - schedulerName: foo-scheduler
    pluginConfig:
      - name: NodeAffinity
        args:
          addedAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: scheduler-profile
                      operator: In
                      values:
                        - foo
      - name: PodTopologySpread
        args:
          defaultConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
          defaultingType: List
## 默认的拓扑分布约束
# defaultConstraints:
#   - maxSkew: 3
#     topologyKey: "kubernetes.io/hostname"
#     whenUnsatisfiable: ScheduleAnyway
#   - maxSkew: 5
#     topologyKey: "topology.kubernetes.io/zone"
#     whenUnsatisfiable: ScheduleAnyway
